let guideMode='guide';
function setGuideMode(mode,btn){guideMode=mode;document.querySelectorAll('.role-tabs button').forEach(b=>b.classList.remove('active'));btn.classList.add('active')}
function openAssistant(){document.getElementById('assistant').classList.add('open');document.querySelector('.assistant-orb').style.display='none';updateAssistantContext()}
function closeAssistant(){stopSpeaking();document.getElementById('assistant').classList.remove('open');document.querySelector('.assistant-orb').style.display='block'}
function updateAssistantContext(){const el=document.getElementById('assistantContext');if(!el)return;const s=spreads[current];el.textContent=`Current context: ${s.dataset.chapter} · ${s.dataset.title} · Spread ${current+1}`}
function bestPrompt(q){const words=q.toLowerCase().split(/\W+/).filter(w=>w.length>3);let best=null,score=-1;PROMPTS.forEach(p=>{const hay=`${p.name} ${p.cat} ${p.when} ${p.inputs}`.toLowerCase();let s=words.reduce((n,w)=>n+(hay.includes(w)?1:0),0);if(q.toLowerCase().includes(p.name.toLowerCase()))s+=5;if(s>score){score=s;best=p}});return score>0?best:null}
function chapterIndexByTitle(term){term=term.toLowerCase();return spreads.findIndex(s=>(s.dataset.title||'').toLowerCase().includes(term))}
function answerQuestion(){stopSpeaking();const raw=document.getElementById('askInput').value.trim();const q=raw.toLowerCase();const s=spreads[current];let title='Playbook guidance',body='',example='',jump='';const p=bestPrompt(raw);
if(q.includes('daily ai routine')||q.includes('daily rhythm')){title='Set up your Daily AI Routine';body='The routine is already designed for you: Morning Pipeline Brief, Discovery Call Question Builder before calls, CRM Note Writer after calls, and End of Day Recap. Your only setup job is to choose when you will use them and what you will always verify personally.';example='Start with the Morning Pipeline Brief. Paste the tasks, leads, callbacks, renewals and appointments you already have. The prompt will organize them into priorities.';jump='Daily AI Rhythm'}
else if(q.includes('30-day')||q.includes('30 day')||q.includes('unfinished step')){title='Your 30-Day Plan';body='The plan is guided practice, not workflow design. Week 1 sets up your profile and lead response. Week 2 practices follow-up. Week 3 covers quote preparation and objections. Week 4 covers renewal review and your Daily AI Routine. Check an item only after you have tried it.';example='If you are just starting, complete the Prompt Profile and then practice New Lead Response. The playbook supplies both tools.';jump='30 Day Plan'}
else if(guideMode==='prompt'||q.includes('prompt')){if(p){title=p.name;body=`This prompt belongs to ${p.cat}. Use it when ${p.when.toLowerCase()} The inputs you should prepare are: ${p.inputs}.`;example=`Example setup: replace the bracketed fields with a hypothetical prospect and use the output as a teaching example. Avery should help you understand the structure, not make coverage decisions.`;}else{title='Find the right prompt';body='Tell me the situation in plain English—for example “ghosted after quote,” “price objection,” “renewal review,” or “turn notes into a CRM entry.” I will map it to the closest prompt in this vault.'}}
else if(guideMode==='roleplay'||q.includes('role play')||q.includes('role-play')||q.includes('pretend')){title='Practice scenario';body='I will play the prospect for this exercise. You respond using the framework in the playbook. After your response, compare it against three things: did you clarify the real issue, did you stay specific to known facts, and did you create one clear next step?';if(q.includes('price')||q.includes('expensive'))example='Prospect: “I appreciate the quote, but it is more than I expected and I found something cheaper online. I’m probably going to go with that.”';else if(q.includes('think'))example='Prospect: “Everything looks fine. I just need to think about it for a while.”';else example='Prospect: “I’m interested, but I’m not sure I want to make a change right now.”'}
else if(guideMode==='example'||q.includes('example')){title='Live example';if(q.includes('three')||q.includes('day 3')||q.includes('follow')){body='The Day 3 framework should add context instead of sending another generic check-in.';example='Example: “Hi Jordan — when we spoke, keeping the monthly cost manageable without losing the protection you care about was the main priority. If you are comparing options, I can help you look at one specific difference so you are comparing them fairly. Want me to walk through that with you?”';jump='Follow Up'}else if(q.includes('price')||q.includes('expensive')){body='The playbook treats price as a diagnostic signal before it becomes a persuasion exercise.';example='Example coach question: “When you say it feels high, are you mainly comparing the total price, or is there a specific part of the recommendation you want to understand better?”';jump='Objections'}else{body=`Here is how to turn the ${s.dataset.title} lesson into an example: use a fictional prospect, state only the facts they have given you, demonstrate one playbook principle, and end with one next step.`;example='Ask me for a specific scenario and I will keep the example tied to this playbook rather than inventing carrier or policy facts.'}}
else {if(q.includes('price')||q.includes('expensive')||q.includes('cost')){title='Price objection framework';body='Do not argue with the price first. Clarify what the prospect is comparing, verify whether the comparison is actually like-for-like, then explain the meaningful difference using verified information. The objective is clarity, not pressure.';example='Coach move: ask one diagnostic question before offering an explanation.';jump='Objections'}else if(q.includes('three day')||q.includes('3 day')||q.includes('follow')){title='Follow-up guidance';body='For a three-day follow-up, avoid “just checking in.” Reference the prospect’s stated priority, add one useful comparison or clarification point, and ask a low-friction question.';example='Try: “When we spoke, you said ___ mattered most. If you’re comparing options, would it help if we looked at ___ together?”';jump='Follow Up'}else if(q.includes('renew')){title='Renewal review guidance';body='Start before urgency. Confirm changes, prepare questions, identify possible discussion areas without assuming gaps, verify actual policy or carrier facts in approved sources, and document the next action.';jump='Retention'}else if(q.includes('lead')||q.includes('prospect')){title='Lead response guidance';body='Fast acknowledgement matters, but relevance matters too. Use what you actually know, avoid interrogating the prospect in the first message, and ask for one easy next step.';jump='Lead Response'}else if(q.includes('what page')||q.includes('where am i')||q.includes('where are we')){title='You are here';body=`You are currently reading ${s.dataset.chapter} · ${s.dataset.title}, spread ${current+1} of ${spreads.length}. I can explain this lesson or help you practice it.`}else{title=`About ${s.dataset.title}`;body=`You are in ${s.dataset.chapter} · ${s.dataset.title}. I can explain this part of the playbook, show a hypothetical example, help you practice the framework, or find the closest prompt in the vault. Ask about the lesson rather than agency operations and I will stay inside the playbook specialist role.`}}
let html=`<div class="answer-label">${guideMode} · ${s.dataset.title}</div><h4>${title}</h4><p>${body}</p>`;if(example)html+=`<div class="example-box">${example}</div>`;if(p&&guideMode!=='prompt')html+=`<div class="example-box"><b>Related prompt:</b> ${p.name}</div>`;if(jump){const idx=chapterIndexByTitle(jump);if(idx>=0)html+=`<button class="jump" onclick="goTo(${idx});closeAssistant()">Open ${jump} chapter</button>`}document.getElementById('assistantAnswer').innerHTML=html;if(document.getElementById('voiceAuto')?.checked)speakAnswer();}

let recognition=null,isListening=false;
function toggleVoice(){if(isListening){recognition?.stop();return} stopSpeaking(); const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){document.getElementById('assistantAnswer').innerHTML='<div class="answer-label">Voice</div><p>Speech recognition is not available in this browser. You can still type to Avery.</p>';return} recognition=new SR();recognition.continuous=false;recognition.interimResults=true;recognition.lang='en-US';recognition.onstart=()=>{isListening=true;const b=document.getElementById('micBtn');b.classList.add('live');b.textContent='Listening…'};recognition.onresult=e=>{let t='';for(let i=e.resultIndex;i<e.results.length;i++)t+=e.results[i][0].transcript;document.getElementById('askInput').value=t};recognition.onend=()=>{isListening=false;const b=document.getElementById('micBtn');b.classList.remove('live');b.textContent='🎙 Speak';if(document.getElementById('askInput').value.trim())answerQuestion()};recognition.start()}
function speakAnswer(){stopSpeaking();const text=document.getElementById('assistantAnswer').innerText;if(!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(text);u.rate=1.02;u.pitch=1;window.speechSynthesis.speak(u)}
function stopSpeaking(){if('speechSynthesis'in window)window.speechSynthesis.cancel()}
document.getElementById('assistantAnswer').addEventListener('dblclick',speakAnswer);
document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')nextSpread();if(e.key==='ArrowLeft')prevSpread();if(e.key==='Escape')closeAssistant()});
initVault();render();updateProgress();updateAssistantContext();