import React, { useState } from 'react';
import { PRICING_TIERS } from '../data/products';
import { CheckCircle2, Sparkles, HelpCircle, ShieldCheck, ArrowRight } from 'lucide-react';
import { toast } from 'sonner';

interface PricingPageProps {
  onOpenWaitlist: () => void;
}

export const PricingPage: React.FC<PricingPageProps> = ({ onOpenWaitlist }) => {
  const [isAnnual, setIsAnnual] = useState(true);
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  const faqs = [
    {
      q: 'How does the "Try Your First Deal Free" strategy work?',
      a: 'You can test the full OCG Deal Analyzer engine with 1 complete deal underwriting run with zero credit card required. Experience sub-millisecond math and instant PDF export before subscribing.'
    },
    {
      q: 'Are financial calculations generated by AI?',
      a: 'No. All financial calculations (Cap Rate, Cash-on-Cash, DSCR, 10-Year Projections) run on a deterministic TypeScript math engine. Zero AI hallucination risk.'
    },
    {
      q: 'Can I upgrade or cancel my subscription anytime?',
      a: 'Yes. Subscriptions can be managed directly in the Customer Portal with instant tier updates or cancellation.'
    },
    {
      q: 'Do you offer custom enterprise GCP Cloud Run deployments?',
      a: 'Yes. Enterprise clients receive a private dedicated GCP Cloud Run container, custom CRM webhooks, and tailored AI model fine-tuning.'
    }
  ];

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-16">
      
      {/* Header */}
      <div className="text-center max-w-3xl mx-auto space-y-4">
        <span className="inline-block px-3 py-1 rounded-full text-xs font-mono bg-cyan-950 text-cyan-400 border border-cyan-800">
          Transparent Tier Matrix
        </span>
        <h1 className="font-heading font-extrabold text-4xl sm:text-5xl text-white">
          Predictable Pricing for Growing Operators
        </h1>
        <p className="text-slate-300 text-sm sm:text-base leading-relaxed">
          Start with our "Try Your First Deal Free" strategy. Upgrade as your deal volume scales.
        </p>

        {/* Monthly vs Annual Toggle */}
        <div className="flex items-center justify-center gap-3 pt-4">
          <span className={`text-xs font-semibold ${!isAnnual ? 'text-white' : 'text-slate-400'}`}>Monthly Billing</span>
          <button
            onClick={() => setIsAnnual(!isAnnual)}
            className="w-14 h-7 rounded-full bg-slate-900 border border-slate-800 p-1 flex items-center transition-all cursor-pointer"
          >
            <div className={`w-5 h-5 rounded-full bg-cyan-400 shadow-md transform transition-transform ${isAnnual ? 'translate-x-7' : 'translate-x-0'}`} />
          </button>
          <div className="flex items-center gap-1.5">
            <span className={`text-xs font-semibold ${isAnnual ? 'text-white' : 'text-slate-400'}`}>Annual Billing</span>
            <span className="px-2 py-0.5 rounded-full text-[10px] font-mono bg-emerald-950 text-emerald-400 border border-emerald-800 font-bold">
              SAVE 20%
            </span>
          </div>
        </div>
      </div>

      {/* Free Strategy Callout Banner */}
      <div className="glass-panel p-6 rounded-3xl border border-cyan-800/80 bg-gradient-to-r from-cyan-950/40 via-slate-900 to-emerald-950/40 flex flex-col sm:flex-row items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="p-3 rounded-2xl bg-cyan-950 text-cyan-400 border border-cyan-800">
            <Sparkles className="w-6 h-6" />
          </div>
          <div>
            <h3 className="font-heading font-bold text-lg text-white">Try Your First Deal 100% Free</h3>
            <p className="text-xs text-slate-300">Test live underwriting math on your current property lead with zero risk.</p>
          </div>
        </div>
        <button
          onClick={onOpenWaitlist}
          className="px-6 py-3 rounded-xl bg-gradient-to-r from-cyan-400 to-emerald-400 text-slate-950 font-extrabold text-xs shadow-lg flex-shrink-0"
        >
          Claim Free Pass
        </button>
      </div>

      {/* Pricing Matrix Cards */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {PRICING_TIERS.map((tier) => {
          const price = isAnnual ? tier.priceAnnual : tier.priceMonthly;
          return (
            <div
              key={tier.id}
              className={`glass-card p-8 rounded-3xl space-y-6 flex flex-col justify-between relative ${
                tier.highlighted
                  ? 'border-2 border-cyan-500 shadow-2xl shadow-cyan-950/50 bg-slate-900/90'
                  : 'border border-slate-800'
              }`}
            >
              {tier.badge && (
                <div className="absolute -top-3.5 left-1/2 -translate-x-1/2 px-3 py-1 rounded-full text-[10px] font-mono bg-gradient-to-r from-cyan-400 to-emerald-400 text-slate-950 font-extrabold shadow-md">
                  {tier.badge}
                </div>
              )}

              <div className="space-y-4">
                <h3 className="font-heading font-bold text-2xl text-white">{tier.title}</h3>
                <p className="text-xs text-slate-400 leading-relaxed">{tier.subtitle}</p>

                <div className="flex items-baseline gap-1 pt-2">
                  <span className="font-mono text-4xl font-extrabold text-white">${price}</span>
                  <span className="text-xs text-slate-400">/ month</span>
                </div>

                <div className="space-y-2.5 pt-4 border-t border-slate-800">
                  {tier.features.map((feat, idx) => (
                    <div key={idx} className="flex items-start gap-2 text-xs text-slate-300">
                      <CheckCircle2 className="w-4 h-4 text-cyan-400 flex-shrink-0 mt-0.5" />
                      <span>{feat}</span>
                    </div>
                  ))}
                </div>
              </div>

              <button
                onClick={onOpenWaitlist}
                className={`w-full py-3.5 rounded-xl font-extrabold text-xs transition-all ${
                  tier.highlighted
                    ? 'bg-gradient-to-r from-cyan-400 via-emerald-400 to-amber-400 text-slate-950 shadow-lg shadow-cyan-500/20 hover:opacity-95'
                    : 'bg-slate-800 hover:bg-slate-700 text-white'
                }`}
              >
                {tier.ctaText}
              </button>
            </div>
          );
        })}
      </div>

      {/* FAQ Accordion */}
      <div className="max-w-3xl mx-auto space-y-6 pt-6">
        <div className="text-center space-y-2">
          <h2 className="font-heading font-extrabold text-2xl text-white">Frequently Asked Questions</h2>
          <p className="text-xs text-slate-400">Everything you need to know about OCG Lab licensing.</p>
        </div>

        <div className="space-y-3">
          {faqs.map((faq, idx) => {
            const isOpen = openFaq === idx;
            return (
              <div
                key={idx}
                className="glass-card rounded-2xl border border-slate-800 overflow-hidden"
              >
                <button
                  onClick={() => setOpenFaq(isOpen ? null : idx)}
                  className="w-full p-4 text-left font-heading font-bold text-sm text-white flex items-center justify-between gap-4"
                >
                  <span>{faq.q}</span>
                  <HelpCircle className={`w-4 h-4 text-cyan-400 transition-transform ${isOpen ? 'rotate-180' : ''}`} />
                </button>
                {isOpen && (
                  <div className="px-4 pb-4 text-xs text-slate-300 border-t border-slate-800/60 pt-3 leading-relaxed">
                    {faq.a}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

    </div>
  );
};
