const spreads=[...document.querySelectorAll('.spread')];
let current=Number(localStorage.getItem(STORAGE_KEY+'-spread')||0);if(current<0||current>=spreads.length)current=0;
const chapterList=document.getElementById('chapterList');
spreads.forEach((s,i)=>{const b=document.createElement('button');b.innerHTML=`<span>${s.dataset.chapter}</span><span>${s.dataset.title}</span><span class="chapter-status">•</span>`;b.onclick=()=>goTo(i);b.dataset.index=i;chapterList.appendChild(b)});
function render(dir=0){spreads.forEach((s,i)=>{s.classList.toggle('active',i===current);if(i===current&&dir){s.querySelectorAll('.page').forEach(p=>{p.classList.remove('turn-next','turn-prev');void p.offsetWidth;p.classList.add(dir>0?'turn-next':'turn-prev')})}});document.querySelectorAll('.chapter-list button').forEach(b=>b.classList.toggle('active',Number(b.dataset.index)===current));document.getElementById('prevBtn').disabled=current===0;document.getElementById('nextBtn').disabled=current===spreads.length-1;document.getElementById('spreadCounter').textContent=`Spread ${current+1} of ${spreads.length}`;localStorage.setItem(STORAGE_KEY+'-spread',current);markRead(current);updateAssistantContext();window.scrollTo({top:0,behavior:'smooth'})}
function nextSpread(){if(current<spreads.length-1){current++;render(1)}} function prevSpread(){if(current>0){current--;render(-1)}} function goTo(i){const dir=i>current?1:-1;current=i;render(dir)}
function markRead(i){let read=JSON.parse(localStorage.getItem(STORAGE_KEY+'-read')||'[]');if(!read.includes(i)){read.push(i);localStorage.setItem(STORAGE_KEY+'-read',JSON.stringify(read))}updateProgress()}
function assignmentStatus(){const daily=[...document.querySelectorAll('[data-save^="daily"]')];const dailyDone=daily.length>0&&daily.every(x=>x.value.trim());const checks=[...document.querySelectorAll('[data-check]')];const planDone=checks.length>0&&checks.every(x=>x.checked);return {dailyDone,planDone}}
function updateCompletionUI(){const read=new Set(JSON.parse(localStorage.getItem(STORAGE_KEY+'-read')||'[]'));document.querySelectorAll('.chapter-list button').forEach(b=>{const done=read.has(Number(b.dataset.index));b.classList.toggle('complete',done);const s=b.querySelector('.chapter-status');if(s)s.textContent=done?'✓':'•'});const a=assignmentStatus();[['assignment-daily',a.dailyDone],['assignment-plan',a.planDone]].forEach(([id,done])=>{const el=document.getElementById(id);if(el){el.classList.toggle('complete',done);el.querySelector('.assignment-check').textContent=done?'✓':'•'}});const p=document.getElementById('pagesReadText');if(p)p.textContent=`${read.size} / ${spreads.length}`;const at=document.getElementById('assignmentsText');if(at)at.textContent=`${Number(a.dailyDone)+Number(a.planDone)} / 2`}
function updateProgress(){const read=new Set(JSON.parse(localStorage.getItem(STORAGE_KEY+'-read')||'[]'));const checks=[...document.querySelectorAll('[data-check]')];const checked=checks.filter(x=>x.checked).length;const fields=[...document.querySelectorAll('[data-save^="daily"]')];const filled=fields.filter(x=>x.value.trim()).length;const total=Math.max(1,spreads.length+checks.length+fields.length);const done=read.size+checked+filled;const pct=Math.round(done/total*100);document.getElementById('progressFill').style.width=pct+'%';document.getElementById('progressText').textContent=pct+'% complete';updateCompletionUI()}
function toggleTheme(){document.body.classList.toggle('dark');localStorage.setItem(STORAGE_KEY+'-theme',document.body.classList.contains('dark')?'dark':'light')} if(localStorage.getItem(STORAGE_KEY+'-theme')==='dark')document.body.classList.add('dark');
async function copyExact(text,btn){const original=btn?.textContent||'Copy Prompt';let ok=false;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(String(text).trim());ok=true}}catch(e){}if(!ok){const ta=document.createElement('textarea');ta.value=String(text).trim();ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();try{ok=document.execCommand('copy')}catch(e){}ta.remove()}if(btn){btn.textContent=ok?'Prompt Copied ✓':'Select + Copy';setTimeout(()=>btn.textContent=original,1200)}}
function copyText(id,btn){const el=document.getElementById(id);return copyExact(el?el.textContent:'',btn)} function copyPromptText(text,btn){return copyExact(text,btn)}
function saveFields(){document.querySelectorAll('[data-save]').forEach(el=>{const key=STORAGE_KEY+'-field-'+el.dataset.save;el.value=localStorage.getItem(key)||'';el.addEventListener('input',()=>{localStorage.setItem(key,el.value);updateProgress();renderVault()})})}
document.querySelectorAll('[data-check]').forEach(el=>{const key=STORAGE_KEY+'-check-'+el.dataset.check;el.checked=localStorage.getItem(key)==='1';el.addEventListener('change',()=>{localStorage.setItem(key,el.checked?'1':'0');updateProgress()})});saveFields();
function resetAll(){if(confirm('Reset reading progress, checklist and worksheet answers on this device?')){Object.keys(localStorage).filter(k=>k.startsWith(STORAGE_KEY)).forEach(k=>localStorage.removeItem(k));location.reload()}}
function profile(){return {strategy:localStorage.getItem(STORAGE_KEY+'-field-profile_lines')||'Not set yet',buybox:localStorage.getItem(STORAGE_KEY+'-field-profile_audience')||'Not set yet',rules:localStorage.getItem(STORAGE_KEY+'-field-profile_tone')||'Conservative, evidence-first',market:localStorage.getItem(STORAGE_KEY+'-field-profile_market')||'Not specified',verify:localStorage.getItem(STORAGE_KEY+'-field-profile_rules')||'Verify comps, bids, lender terms, title, taxes, insurance and legal documents before committing capital.'}}
