let guideMode='guide';
function setGuideMode(mode,btn){guideMode=mode;document.querySelectorAll('.role-tabs button').forEach(b=>b.classList.remove('active'));btn.classList.add('active')}
function openAssistant(){document.getElementById('assistant').classList.add('open');document.querySelector('.assistant-orb').style.display='none';updateAssistantContext()}
function closeAssistant(){stopSpeaking();document.getElementById('assistant').classList.remove('open');document.querySelector('.assistant-orb').style.display='block'}
function updateAssistantContext(){const el=document.getElementById('assistantContext');if(!el)return;const s=spreads[current];el.textContent=`Current context: ${s.dataset.chapter} · ${s.dataset.title} · Spread ${current+1}`}
function bestPrompt(q){const words=q.toLowerCase().split(/\W+/).filter(w=>w.length>3);let best=null,score=-1;PROMPTS.forEach(p=>{const hay=`${p.name} ${p.cat} ${p.text}`.toLowerCase();let s=words.reduce((n,w)=>n+(hay.includes(w)?1:0),0);if(q.toLowerCase().includes(p.name.toLowerCase()))s+=6;if(s>score){score=s;best=p}});return score>0?best:null}
function answerQuestion(){stopSpeaking();const raw=document.getElementById('askInput').value.trim();const s=spreads[current];const p=bestPrompt(raw);let title='Playbook guidance',body='',example='';
if(!raw){body=`You are reading ${s.dataset.title}. Ask me to explain the lesson, show an investor example, find a prompt, or stress-test a decision.`}
else if(guideMode==='prompt'||/prompt|which tool|find/i.test(raw)){if(p){title=p.name;body=`Use this ${p.cat} workflow for the situation you described. It requires verified deal facts and must keep unknowns visible.`;example=p.text}else body='Describe the decision in plain English—such as rehab budget, DSCR, comps, financing, offer strategy, title risk or postmortem—and I will map it to the closest workflow.'}
else if(guideMode==='roleplay'||/stress|kill|downside|risk/i.test(raw)){title='Independent stress test';body='Start by separating verified facts from assumptions and missing evidence. Then challenge the first variable most likely to destroy margin: basis, rehab, timeline, value/rent, financing, or exit. A deal stays REVIEW until material gaps are verified.';example='Example: If ARV is based on weak comps and rehab has no trade bids, the correct state is REVIEW—not PASS—even if the projected profit looks strong.'}
else if(guideMode==='example'||/example/i.test(raw)){title='Investor example';body=`Apply the ${s.dataset.title} lesson to a hypothetical property while keeping all unverified values labeled as assumptions.`;example='Example framework: Verified facts → Missing facts → Authorized assumptions → Downside case → Decision gate → Next evidence required.'}
else if(/dscr|rental|brrrr/i.test(raw)){title='Rental / DSCR discipline';body='Use verified rent, taxes, insurance, operating expenses, loan terms and lender criteria. Calculate only what the inputs support. Never manufacture DSCR requirements or stabilized rent.'}
else if(/rehab|scope|contractor/i.test(raw)){title='Rehab discipline';body='Separate scope from price. Build the room/trade scope first, compare actual bids second, and use AI to expose omissions, sequencing risk and contingency—not to invent contractor pricing.'}
else if(/offer|seller|negotiat/i.test(raw)){title='Acquisition discipline';body='Anchor the offer to verified underwriting and a defined walk-away. Separate seller needs from your economics, then identify concessions you can trade without breaking margin or risk limits.'}
else if(/comp|arv|rent/i.test(raw)){title='Market evidence';body='Use actual sales or rental comps. Explain qualitative differences and uncertainty. Do not create nonexistent comps or pretend an exact adjustment is known when it is not.'}
else {title=`About ${s.dataset.title}`;body='Use the framework on this spread: verified evidence first, explicit assumptions second, downside challenge third, and a clear PASS / REVIEW / KILL gate. Grant can help structure the work but cannot replace field, lender, title, legal, tax or market verification.'}
let html=`<div class="answer-label">${guideMode} · ${s.dataset.title}</div><h4>${title}</h4><p>${body}</p>`;if(example)html+=`<div class="example-box">${example}</div>`;if(p&&guideMode!=='prompt')html+=`<div class="example-box"><b>Related prompt:</b> ${p.name}</div>`;document.getElementById('assistantAnswer').innerHTML=html}
