const STORAGE_KEY='ocg-rei-playbook-v3';
const PROMPTS=[
['Deal Intake','Deal Intake Normalizer','Normalize this real-estate investment opportunity into a decision-ready deal brief. Use only the facts I provide. Separate known facts, missing facts, assumptions I explicitly authorize, and questions that must be answered before underwriting. Do not invent values.'],
['Deal Intake','Missing Information Finder','Review the deal information I provide and identify every missing fact that could materially affect value, rehab, financing, rent, exit strategy, title, taxes, insurance, utilities, occupancy, or timeline. Rank each missing item High, Medium, or Low impact.'],
['Deal Intake','Seller Motivation Brief','Using only my notes, summarize the seller situation, stated motivation, timing, decision-makers, known constraints, and unanswered questions. Do not infer motivation that was not stated.'],
['Underwriting','AI Deal Stress Test','Stress-test this real-estate investment deal. Inputs: property facts, acquisition price, rehab, ARV or stabilized value, rents, financing, holding costs, exit assumptions, and any known risks. First identify missing information. Then test downside cases for price, rehab, timeline, value, rent, rate, and vacancy. Finish with a decision: PASS, REVIEW, or KILL, plus the exact reasons. Never invent missing numbers.'],
['Underwriting','Fix & Flip Underwriter','Underwrite this fix-and-flip using only my inputs. Calculate total project cost, financing cost if provided, selling costs if provided, gross profit, net profit, ROI, and margin on cost. Show formulas and flag any assumption I did not provide instead of guessing.'],
['Underwriting','BRRRR Underwriter','Evaluate this BRRRR deal using my acquisition, rehab, stabilized value, rent, taxes, insurance, operating costs, refinance LTV, rate, term, and seasoning assumptions. Calculate cash left in the deal, refinance proceeds, DSCR if inputs permit, and major risks.'],
['Underwriting','Rental / DSCR Analyzer','Analyze this rental or DSCR opportunity. Calculate NOI, DSCR, cap rate, cash flow, cash-on-cash return, break-even occupancy, and sensitivity to rate, vacancy, taxes, insurance, and repairs. Do not manufacture lender criteria.'],
['Underwriting','Maximum Allowable Offer','Calculate a maximum allowable offer using the strategy and constraints I provide. Show the formula, every input, and a sensitivity range. If I have not provided a required input, stop and ask for it.'],
['Rehab','Scope Builder','Turn my property notes, inspection findings, photos described in text, and renovation goals into a room-by-room scope of work. Separate required repairs, value-add improvements, optional upgrades, and unknowns requiring field verification.'],
['Rehab','Rehab Budget Challenger','Audit my rehab budget for omissions, unrealistic allowances, double-counting, contingency, permits, dumpsters, utilities, carrying costs, and trade sequencing. Do not replace contractor bids with invented estimates.'],
['Rehab','Contractor Bid Comparator','Compare the contractor bids I provide line by line. Normalize scope differences, exclusions, allowances, schedule, payment terms, warranty, and change-order exposure. Identify the lowest-risk bid, not merely the cheapest.'],
['Rehab','Renovation Sequence Planner','Build a dependency-aware renovation sequence from my scope. Identify permits, long-lead items, inspections, trade dependencies, critical path, and work that can run in parallel.'],
['Financing','Financing Option Comparator','Compare the financing options I provide across cash required, rate, points, fees, interest method, term, extension fees, draw process, LTC/LTV, recourse, prepayment, seasoning, and exit risk. Rank them for this specific deal.'],
['Financing','Hard Money Cost Model','Using only the lender terms I provide, model total borrowing cost for multiple hold periods. Include points, fees, interest, draws, extension fees, and payoff assumptions when provided.'],
['Financing','DSCR Loan Readiness','Review this rental deal for DSCR loan readiness using the lender requirements and property numbers I provide. Identify what passes, what fails, what is unknown, and what documentation is still needed.'],
['Financing','Creative Finance Risk Review','Analyze this proposed seller-finance, subject-to, wrap, second-lien, or other creative-finance structure. Separate economic upside from legal, title, due-on-sale, servicing, tax, insurance, and execution risks. Recommend professional review where required.'],
['Acquisition','Offer Strategy Builder','Build an offer strategy from the deal facts, seller situation, underwriting, financing constraints, and walk-away number I provide. Give me primary offer, fallback structure, concessions I can trade, and the exact conditions that should make me walk.'],
['Acquisition','Negotiation Prep','Prepare me for a seller or agent negotiation. Summarize my leverage, their stated needs, my non-negotiables, likely objections, questions to ask, and three compliant response options.'],
['Acquisition','Due Diligence Checklist','Create a deal-specific due-diligence checklist covering title, taxes, liens, zoning, permits, utilities, leases, occupancy, environmental concerns, insurance, flood, HOA, survey, access, condition, and financing requirements.'],
['Acquisition','Kill-the-Deal Committee','Act as an independent kill-the-deal committee. Argue the strongest case against buying this property. Focus on downside, missing evidence, execution risk, financing risk, exit risk, and opportunity cost. Finish with KILL, REVIEW, or PROCEED TO NEXT GATE.'],
['Market','Comp Review','Analyze the sales comps I provide. Adjust qualitatively for location, size, condition, bed/bath count, lot, garage, basement, updates, concessions, and sale timing. Do not invent comps or exact adjustments I have not supplied.'],
['Market','Rent Comp Review','Analyze the rental comps I provide and produce a defendable rent range. Flag differences in utilities, furnishings, lease term, condition, amenities, concessions, and tenant-paid expenses.'],
['Market','Neighborhood Risk Brief','Using the market information I provide, summarize demand drivers, supply, vacancy, employer concentration, taxes, insurance, regulatory issues, rent pressure, resale liquidity, and any data gaps that require research.'],
['Market','Exit Strategy Comparator','Compare flip, long-term rental, BRRRR, midterm rental, wholesale, and resale-as-is only where relevant to the facts I provide. Rank by expected return, capital required, execution difficulty, liquidity, and downside risk.'],
['Operations','Weekly Portfolio Review','Turn my portfolio data into a weekly operating brief: cash, debt, vacancies, delinquency, repairs, turns, leases, insurance, taxes, capex, refinance dates, and the five actions that matter most this week.'],
['Operations','Property Manager Brief','Create a concise property-manager action brief from the issues and tenant/property facts I provide. Separate urgent safety or habitability issues, financial issues, routine maintenance, leasing, and follow-up.'],
['Operations','Maintenance Triage','Triage these property maintenance requests by emergency, urgent, routine, cosmetic, and monitor. Explain why, identify missing details, and draft the questions I should ask before dispatching a vendor.'],
['Operations','Turnover Plan','Build a make-ready plan for this vacancy using the condition, scope, vendors, leasing target, and deadline I provide. Identify the critical path and the fastest safe path back to rent-ready.'],
['Disposition','Listing Prep Brief','Create an investor disposition brief for a renovated property: target buyer, strongest improvements, documentation to gather, likely objections, unresolved items, showing readiness, and launch checklist.'],
['Disposition','Offer Comparison','Compare the purchase offers I provide on net proceeds, financing strength, contingencies, appraisal risk, inspection risk, concessions, closing timing, and probability of closing.'],
['Disposition','Pre-Closing Risk Check','Audit this transaction before closing. Identify unresolved title, repair, lender, appraisal, insurance, utility, occupancy, document, possession, and funds-flow risks.'],
['Scaling','Deal Pipeline Prioritizer','Rank the deals in my pipeline by expected value, certainty, time requirement, capital requirement, strategic fit, and downside. Tell me what to pursue, pause, delegate, or kill.'],
['Scaling','Capital Allocation Review','Review how I plan to allocate available capital across acquisitions, rehab, reserves, debt reduction, marketing, and operating needs. Stress-test liquidity and concentration risk.'],
['Scaling','Postmortem','Run a no-excuses postmortem on this completed or failed deal. Compare original assumptions with actual results, identify root causes, separate controllable from uncontrollable factors, and create rules for the next acquisition.'],
['Scaling','SOP Builder','Turn this repeatable real-estate investing process into a clear SOP with trigger, owner, inputs, steps, decision gates, evidence required, output, escalation path, and completion standard.'],
['Scaling','Investor Decision Memo','Turn all verified deal information into a one-page investment decision memo with thesis, numbers, financing, rehab, market, risks, missing facts, downside case, and final PASS / REVIEW / KILL recommendation.']
];

const spreads=[
{chapter:'Start',title:'Cover',left:`<div class="physical-book"><div class="book-spine"></div><div class="retail-cover"><img src="/assets/approved-logo.png" alt="OCG LAB"/><div class="series">PROFESSIONAL PLAYBOOKS</div><h1>REAL ESTATE<br/>INVESTOR <span>AI PLAYBOOK</span></h1><p>Source smarter. Underwrite harder. Protect the margin.</p><div class="cover-flow">SOURCE → ANALYZE → STRESS TEST → DECIDE → EXECUTE</div><div class="cover-signature">BUILD · AUTOMATE · CREATE · SCALE</div></div></div>`,right:`<div class="opening"><div class="kicker">OCG LAB Professional Playbooks</div><blockquote>Buy the numbers.<br/><span class="grad">Protect the margin.</span></blockquote><p>This is a decision system for real-estate investors. It helps you organize facts, challenge assumptions, stress-test downside, prepare execution, and make disciplined acquisition decisions without inventing missing information.</p><div class="metric-row"><div class="metric"><b>36</b><span>investor prompts</span></div><div class="metric"><b>30</b><span>day implementation plan</span></div><div class="metric"><b>3</b><span>decision outcomes: PASS / REVIEW / KILL</span></div></div><div class="signature">BUILD   |   AUTOMATE   |   CREATE   |   SCALE</div></div>`},
{chapter:'01',title:'Operating System',left:`<div class="kicker">Chapter 1</div><div class="chapter-index">01</div><h2>The Investor<br/><span class="grad">Operating System</span></h2><p class="sub">One repeatable flow from raw opportunity to evidence-backed decision.</p>`,right:`<div class="kicker">The Big Picture</div><h2 class="chapter-title">One system.<br/>Six gates.</h2><div class="visual-system"><div class="node"><i>1</i><b>Source</b><span>Capture the opportunity.</span></div><div class="node"><i>2</i><b>Verify</b><span>Separate facts from gaps.</span></div><div class="node"><i>3</i><b>Underwrite</b><span>Model the strategy.</span></div><div class="node"><i>4</i><b>Stress Test</b><span>Challenge downside.</span></div><div class="node"><i>5</i><b>Decide</b><span>PASS / REVIEW / KILL.</span></div></div><div class="callout"><b>The rule</b><p>Never let AI fill missing deal facts with guesses. Unknown stays unknown until verified.</p></div>`},
{chapter:'02',title:'Meet Grant',left:`<div class="kicker">Chapter 2 · Your Playbook Specialist</div><h2 class="chapter-title">Meet <span class="grad">Grant.</span></h2><p class="sub">Grant is the specialist inside this playbook. He helps you understand, practice, and apply the investor workflows.</p><div class="avery-hero"><div class="avery-identity"><div class="avery-orb-lg"></div><div><small>OCG LAB PLAYBOOK SPECIALIST</small><h3>Grant</h3><p>Real Estate Investor AI Playbook Guide</p></div></div><div class="avery-mission"><strong>Grant’s mission:</strong> help you use this book to make better real-estate investment decisions. Ask for an explanation, a deal example, a stress test, or the right prompt for the problem in front of you.</div></div>`,right:`<div class="kicker">How Grant Fits</div><h2 class="chapter-title">A coach inside the book.<br/><span class="grad">Not a substitute for evidence.</span></h2><div class="cards"><div class="card"><span class="tag">GRANT CAN</span><h3>Teach and challenge</h3><p>Explain workflows, find prompts, structure analysis, challenge assumptions, and help you prepare decisions.</p></div><div class="card"><span class="tag">GRANT DOES NOT</span><h3>Invent or authorize</h3><p>Grant does not invent comps, bids, lender terms, title facts, rents, ARV, legal conclusions, or final professional approvals.</p></div></div><div class="callout"><b>Context-aware by design.</b><p>Grant knows which chapter and spread you are reading.</p></div><button class="pill-btn primary" onclick="openAssistant()">Talk to Grant</button>`},
{chapter:'03',title:'Deal Intake',left:`<div class="kicker">Chapter 3</div><h2 class="chapter-title">Start with<br/><span class="grad">clean facts.</span></h2><p class="sub">Before valuation or financing, normalize the opportunity and expose what is missing.</p><div class="cards"><div class="card"><span class="tag">KNOWN</span><h3>Verified facts</h3><p>Address, asking price, occupancy, actual rents, taxes, measurements, bids, lender terms.</p></div><div class="card"><span class="tag">UNKNOWN</span><h3>Information gaps</h3><p>Anything not verified stays visibly unresolved.</p></div></div>`,right:`<div class="kicker">Core Prompt</div><h2 class="chapter-title">Deal intake<br/>normalizer</h2>${promptBox(0)}<div class="callout"><b>Use before underwriting.</b><p>Clean inputs make every later decision better.</p></div>`},
{chapter:'04',title:'Underwriting',left:`<div class="kicker">Chapter 4</div><h2 class="chapter-title">Underwrite the<br/><span class="grad">strategy.</span></h2><p class="sub">Different exits require different math. Keep flip, BRRRR, and rental assumptions separate.</p><div class="cards"><div class="card"><span class="tag">FLIP</span><h3>Margin + time</h3><p>Total project cost, selling costs, net profit, ROI, timeline.</p></div><div class="card"><span class="tag">BRRRR</span><h3>Refi + basis</h3><p>Stabilized value, refinance proceeds, cash left in, DSCR.</p></div><div class="card"><span class="tag">RENTAL</span><h3>NOI + resilience</h3><p>NOI, DSCR, cap rate, cash flow, occupancy sensitivity.</p></div></div>`,right:`<div class="kicker">Flagship Workflow</div><h2 class="chapter-title">AI Deal<br/>Stress Test</h2>${promptBox(3)}<div class="decision-strip"><span>PASS</span><span>REVIEW</span><span>KILL</span></div>`},
{chapter:'05',title:'Rehab',left:`<div class="kicker">Chapter 5</div><h2 class="chapter-title">Control the<br/><span class="grad">scope.</span></h2><p class="sub">A deal can survive a conservative ARV. It rarely survives an uncontrolled scope.</p><div class="cards"><div class="card"><h3>Scope first</h3><p>Room-by-room, trade-by-trade, with unknowns separated.</p></div><div class="card"><h3>Budget second</h3><p>Validate allowances, contingency, permits, utilities, and missed trades.</p></div></div>`,right:`<div class="kicker">Core Prompt</div><h2 class="chapter-title">Rehab budget<br/>challenger</h2>${promptBox(9)}<div class="callout"><b>Do not use AI estimates as contractor bids.</b><p>Use AI to find omissions and challenge logic, then verify pricing in the field.</p></div>`},
{chapter:'06',title:'Financing',left:`<div class="kicker">Chapter 6</div><h2 class="chapter-title">Finance the<br/><span class="grad">whole deal.</span></h2><p class="sub">Rate is only one line. Cash required, points, fees, draws, extensions, recourse, and exit constraints can change the winner.</p><div class="formula">TRUE CAPITAL COST = cash required + fees + interest + friction + exit constraints</div>`,right:`<div class="kicker">Core Prompt</div><h2 class="chapter-title">Financing option<br/>comparator</h2>${promptBox(12)}<div class="callout"><b>Use actual term sheets.</b><p>Do not let a comparison assume lender rules you have not verified.</p></div>`},
{chapter:'07',title:'Acquisition',left:`<div class="kicker">Chapter 7</div><h2 class="chapter-title">Negotiate from<br/><span class="grad">your walk-away.</span></h2><p class="sub">The purpose of an offer strategy is not to win every deal. It is to buy only when the economics and risk fit.</p><div class="cards"><div class="card"><h3>Primary offer</h3><p>Your preferred structure based on verified underwriting.</p></div><div class="card"><h3>Fallback</h3><p>Terms or concessions you can trade without breaking the deal.</p></div><div class="card"><h3>Walk-away</h3><p>The line you will not cross.</p></div></div>`,right:`<div class="kicker">Independent Challenge</div><h2 class="chapter-title">Kill-the-Deal<br/>Committee</h2>${promptBox(19)}<div class="callout"><b>Run this before earnest money goes hard.</b><p>Your best deals should survive the strongest case against them.</p></div>`},
{chapter:'08',title:'Market',left:`<div class="kicker">Chapter 8</div><h2 class="chapter-title">Market evidence<br/><span class="grad">over optimism.</span></h2><p class="sub">ARV and rent are not feelings. They are evidence sets with differences, concessions, timing, and uncertainty.</p><div class="cards"><div class="card"><h3>Sales comps</h3><p>Condition, size, location, lot, garage, basement, timing.</p></div><div class="card"><h3>Rent comps</h3><p>Lease term, utilities, furnishings, amenities, concessions.</p></div></div>`,right:`<div class="kicker">Core Prompt</div><h2 class="chapter-title">Comp review</h2>${promptBox(20)}<div class="callout"><b>No invented comps.</b><p>Provide the actual comp set or connect a verified research source.</p></div>`},
{chapter:'09',title:'Operations',left:`<div class="kicker">Chapter 9</div><h2 class="chapter-title">Own the asset<br/><span class="grad">after closing.</span></h2><p class="sub">Operations protect the underwriting after acquisition.</p><div class="cards"><div class="card"><h3>Weekly portfolio review</h3><p>Cash, debt, vacancy, repairs, turns, leases, taxes, insurance.</p></div><div class="card"><h3>Maintenance triage</h3><p>Emergency, urgent, routine, cosmetic, monitor.</p></div></div>`,right:`<div class="kicker">Core Prompt</div><h2 class="chapter-title">Weekly portfolio<br/>review</h2>${promptBox(24)}<div class="callout"><b>Force prioritization.</b><p>The output should tell you what matters this week, not create another dashboard you ignore.</p></div>`},
{chapter:'10',title:'Prompt Vault',left:`<div class="kicker">Chapter 10</div><h2 class="chapter-title">The <span class="grad">Prompt Vault</span></h2><p class="sub">Thirty-six investor workflows organized by the decision in front of you.</p><div class="vault-search"><input id="promptSearch" placeholder="Search prompts, e.g. DSCR, rehab, offer..." oninput="renderVault()"/><select id="promptCategory" onchange="renderVault()"><option value="">All categories</option></select></div><div id="vaultCount" class="signature"></div>`,right:`<div id="vaultGrid" class="vault-grid"></div>`},
{chapter:'11',title:'30-Day Plan',left:`<div class="kicker">Chapter 11</div><h2 class="chapter-title">30-Day<br/><span class="grad">Implementation</span></h2><p class="sub">Install the system around real deals, not hypothetical busywork.</p><div class="timeline"><div><b>Week 1</b><span>Normalize intake + missing facts.</span></div><div><b>Week 2</b><span>Underwrite + stress test.</span></div><div><b>Week 3</b><span>Rehab + financing + acquisition.</span></div><div><b>Week 4</b><span>Portfolio review + postmortem + SOP.</span></div></div>`,right:`<div class="kicker">Assignment</div><h2 class="chapter-title">Build your<br/>decision rhythm</h2><div class="checklist"><label><input type="checkbox" data-task="intake"/> Use the Deal Intake Normalizer on one real opportunity.</label><label><input type="checkbox" data-task="stress"/> Run the AI Deal Stress Test.</label><label><input type="checkbox" data-task="kill"/> Run the Kill-the-Deal Committee.</label><label><input type="checkbox" data-task="memo"/> Create an Investor Decision Memo.</label><label><input type="checkbox" data-task="post"/> Postmortem the result.</label></div><div class="callout"><b>Completion standard</b><p>You can move from raw lead to documented PASS / REVIEW / KILL without hidden assumptions.</p></div>`},
{chapter:'12',title:'Decision Memo',left:`<div class="kicker">Chapter 12</div><h2 class="chapter-title">Finish with a<br/><span class="grad">decision memo.</span></h2><p class="sub">A disciplined investor can explain why the deal deserves capital—or why it does not.</p><div class="cards"><div class="card"><h3>Thesis</h3><p>Why this property, this basis, this strategy, now.</p></div><div class="card"><h3>Evidence</h3><p>Numbers, comps, bids, financing, market, title, due diligence.</p></div><div class="card"><h3>Downside</h3><p>What breaks first and what protects you.</p></div></div>`,right:`<div class="kicker">Final Prompt</div><h2 class="chapter-title">Investor Decision<br/>Memo</h2>${promptBox(35)}<div class="decision-strip"><span>PASS</span><span>REVIEW</span><span>KILL</span></div>`},
{chapter:'Finish',title:'Close',left:`<div class="kicker">Keep the discipline</div><h2 class="chapter-title">The goal is not<br/><span class="grad">more deals.</span></h2><p class="sub">The goal is better decisions, protected capital, and repeatable execution.</p><blockquote style="margin-top:60px">Acquire intelligently.<br/>Transform strategically.<br/><span class="grad">Build lasting value.</span></blockquote>`,right:`<div class="opening"><img src="/assets/approved-logo.png" alt="OCG LAB" style="max-width:250px"/><h2 class="chapter-title" style="margin-top:40px">Real Estate Investor<br/>AI Playbook</h2><p>Return to the Prompt Vault whenever a live deal creates a decision, risk, or execution problem.</p><button class="pill-btn primary" onclick="goToSpread(10)">Open Prompt Vault</button><div class="signature" style="margin-top:60px">OCG LAB · BUILD | AUTOMATE | CREATE | SCALE</div></div>`}
];

function promptBox(i){const p=PROMPTS[i];return `<div class="prompt"><h3>${esc(p[1])}</h3><pre id="p-${i}">${esc(p[2])}\n\nCURRENT SITUATION:\nPaste your verified deal facts here.</pre><button class="copy" onclick="copyPrompt(${i},this)">Copy Prompt</button></div>`}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
let current=Number(localStorage.getItem(STORAGE_KEY+'-spread')||0);let guideMode='guide';
function renderBook(){const book=document.getElementById('book');book.innerHTML=spreads.map((s,i)=>`<section class="spread ${i===current?'active':''}" data-chapter="${s.chapter}" data-title="${esc(s.title)}"><div class="page left ${i===0?'cover-page':''}">${s.left}<div class="page-no">${String(i*2||'OCG LAB').padStart(2,'0')}</div></div><div class="page right">${s.right}<div class="page-no">${String(i*2+1).padStart(2,'0')}</div></div></section>`).join('');buildChapters();restoreTasks();renderVault();updateUI()}
function buildChapters(){const el=document.getElementById('chapterList');el.innerHTML=spreads.map((s,i)=>`<button class="chapter-link ${i===current?'active':''}" onclick="goToSpread(${i})"><span>${s.chapter}</span>${esc(s.title)}</button>`).join('')}
function updateUI(){document.querySelectorAll('.spread').forEach((e,i)=>e.classList.toggle('active',i===current));document.querySelectorAll('.chapter-link').forEach((e,i)=>e.classList.toggle('active',i===current));document.getElementById('spreadCounter').textContent=`Spread ${current+1} of ${spreads.length}`;document.getElementById('prevBtn').disabled=current===0;document.getElementById('nextBtn').disabled=current===spreads.length-1;const pct=Math.round(((current+1)/spreads.length)*100);document.getElementById('progressFill').style.width=pct+'%';document.getElementById('progressText').textContent=pct+'% complete';document.getElementById('pagesReadText').textContent=`${current+1} / ${spreads.length}`;document.getElementById('assistantContext').textContent=`${spreads[current].chapter} · ${spreads[current].title}`;localStorage.setItem(STORAGE_KEY+'-spread',current);window.scrollTo({top:0,behavior:'smooth'})}
function nextSpread(){if(current<spreads.length-1){current++;updateUI()}}
function prevSpread(){if(current>0){current--;updateUI()}}
function goToSpread(i){current=Math.max(0,Math.min(spreads.length-1,i));updateUI()}
function copyPrompt(i,b){navigator.clipboard.writeText(PROMPTS[i][2]+'\n\nCURRENT SITUATION:\nPaste your verified deal facts here.').then(()=>{const old=b.textContent;b.textContent='Copied';setTimeout(()=>b.textContent=old,1200)})}
function renderVault(){const grid=document.getElementById('vaultGrid');if(!grid)return;const q=(document.getElementById('promptSearch')?.value||'').toLowerCase();const cat=document.getElementById('promptCategory')?.value||'';const rows=PROMPTS.map((p,i)=>({...{cat:p[0],title:p[1],body:p[2]},i})).filter(p=>(!cat||p.cat===cat)&&(!q||(p.cat+' '+p.title+' '+p.body).toLowerCase().includes(q)));grid.innerHTML=rows.map(p=>`<article class="vault-card"><span class="tag">${esc(p.cat)}</span><h3>${esc(p.title)}</h3><p>${esc(p.body.slice(0,145))}...</p><button class="copy" onclick="copyPrompt(${p.i},this)">Copy Prompt</button></article>`).join('');document.getElementById('vaultCount').textContent=`${rows.length} of ${PROMPTS.length} prompts`;const sel=document.getElementById('promptCategory');if(sel&&sel.options.length===1){[...new Set(PROMPTS.map(p=>p[0]))].forEach(c=>sel.add(new Option(c,c)))}}
function restoreTasks(){const saved=JSON.parse(localStorage.getItem(STORAGE_KEY+'-tasks')||'{}');document.querySelectorAll('[data-task]').forEach(cb=>{cb.checked=!!saved[cb.dataset.task];cb.addEventListener('change',saveTasks)});updateTaskCount()}
function saveTasks(){const o={};document.querySelectorAll('[data-task]').forEach(cb=>o[cb.dataset.task]=cb.checked);localStorage.setItem(STORAGE_KEY+'-tasks',JSON.stringify(o));updateTaskCount()}
function updateTaskCount(){const a=[...document.querySelectorAll('[data-task]')];const n=a.filter(x=>x.checked).length;const el=document.getElementById('assignmentsText');if(el)el.textContent=`${n} / ${a.length||5}`}
function toggleTheme(){document.body.classList.toggle('reading-mode')}
function openAssistant(){document.getElementById('assistant').classList.add('open')}
function closeAssistant(){document.getElementById('assistant').classList.remove('open')}
function setGuideMode(m,b){guideMode=m;document.querySelectorAll('.role-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active')}
function answerQuestion(){const q=document.getElementById('askInput').value.trim();const out=document.getElementById('assistantAnswer');if(!q){out.innerHTML='<div class="answer-label">Grant</div><p>Ask about the current chapter, request an example, or tell me the deal decision you are working through.</p>';return}const s=spreads[current];let related=PROMPTS.filter(p=>(p[0]+' '+p[1]+' '+p[2]).toLowerCase().split(/\W+/).some(w=>w.length>5&&q.toLowerCase().includes(w))).slice(0,3);if(!related.length)related=PROMPTS.filter(p=>p[0].toLowerCase().includes(s.title.toLowerCase().split(' ')[0])).slice(0,3);out.innerHTML=`<div class="answer-label">Grant · ${esc(s.title)}</div><p><strong>Use the book as a decision framework, not as a source of missing facts.</strong> For “${esc(q)}”, start by separating verified facts from unknowns, then choose the workflow that tests the decision you need to make.</p>${related.length?'<p><strong>Relevant prompts:</strong> '+related.map(p=>esc(p[1])).join(' · ')+'</p>':''}<p>If the result depends on ARV, rents, bids, title, lender rules, legal conclusions, taxes, insurance, or property condition, verify those inputs before acting.</p>`}
function toggleVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert('Voice input is not supported in this browser.');return}const r=new SR();r.lang='en-US';r.onresult=e=>document.getElementById('askInput').value=e.results[0][0].transcript;r.start()}
function stopSpeaking(){speechSynthesis?.cancel()}
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;if(e.key==='ArrowRight')nextSpread();if(e.key==='ArrowLeft')prevSpread()});
document.addEventListener('DOMContentLoaded',renderBook);