(function(){
const prompts=[
['Research','Content Research','Research current mortgage topics for the audience and market I provide. Separate evergreen education from time-sensitive claims. For every current claim include authoritative source evidence, freshness, retrieval timestamp, compliance risk and facts requiring human verification. Return at least three ranked opportunities; never invent rates, programs or eligibility.'],
['Planning','Daily Content Plan','Use my audience, market, approved voice and recent-topic history to rank today’s useful content opportunities. Avoid unnecessary repetition. Return audience, why now, hook, CTA, format, verification needs and compliance risk.'],
['Education','Borrower Education','Explain the borrower topic in plain language. Separate general education from borrower-specific advice. Give one clearly hypothetical example, questions to ask a licensed lender and every fact requiring verification.'],
['Education','First-Time Buyer Education','Create first-time-buyer education without assuming 20% down, qualification, approval, program availability or current rates. Provide a short script, caption, CTA and verification checklist.'],
['Education','Investor Borrower Education','Create investor-borrower education using only verified scenario facts. Flag property, income, reserve, occupancy and program assumptions. Never imply universal qualification.'],
['Partner','Realtor Partner Touch','Draft a value-first Realtor message using the real relationship context. Offer useful buyer education and exclude referral compensation, gifts, kickbacks and quid-pro-quo language.'],
['Follow Up','New Lead Follow-Up','Draft a warm first response to the actual mortgage question, ask the minimum useful questions and offer one clear next step. Do not quote rates, payments, approval likelihood or eligibility unless verified.'],
['Follow Up','No-Response Follow-Up','Using the last real conversation and agreed next step, create a low-pressure text, email, close-the-loop message and later re-entry message. Do not manufacture urgency or imply unchanged approval.'],
['Follow Up','Preapproval Check-In','Create a useful preapproval check-in. Ask about the search and relevant changes, offer updated scenario review and avoid implying approval, terms or pricing remain unchanged.'],
['Milestones','Closing Milestone Update','Turn verified closing status into a concise update: what is complete, what remains, owner, timing and what still needs confirmation. Never promise an unverified closing date or outcome.'],
['Nurture','Past-Client Nurture','Create a helpful homeowner check-in without inventing savings, equity, refinance benefit or market claims. Provide text, email and call opener.'],
['Objections','Objection Coach','Read exactly what the person said. Treat possible concerns as hypotheses, give diagnostic questions, a calm response and one next step. Require verified data before discussing rates, payments, savings, approval or eligibility.'],
['Video','Verified 60-Second Script','Using the selected sourced research bundle, create audience, headline, hook, spoken script, CTA, caption plan, B-roll, disclosures, source mapping and claims requiring verification. Preserve the evidence exactly.'],
['Compliance','Compliance-Safe Rewrite','Rewrite without changing supported facts. Remove or flag guarantees, approval promises, unsupported savings, invented rates, fabricated programs, unverified eligibility and company-policy claims. Return a change log.'],
['Planning','Weekly Lender Plan','Turn authorized pipeline items, commitments and content history into a weekly plan. Rank borrower follow-ups, partner touches, milestones, content and verification tasks. Draft only.']];
const spread=[...document.querySelectorAll('.spread')].find(x=>x.dataset.title==='Prompt Vault'),page=spread?.querySelector('.page.right');if(!page)return;const host=document.createElement('div');host.className='lender-vault';host.innerHTML='<div class="vault-controls"><input aria-label="Search lender prompts" placeholder="Search: buyer stopped replying"><select aria-label="Filter prompt category"><option value="">All categories</option></select></div><div class="vault-grid"></div>';page.querySelector('.page-no')?.before(host);const search=host.querySelector('input'),select=host.querySelector('select'),grid=host.querySelector('.vault-grid');[...new Set(prompts.map(x=>x[0]))].sort().forEach(x=>select.add(new Option(x,x)));
function render(){const term=search.value.toLowerCase(),category=select.value,rows=prompts.filter(x=>(!category||x[0]===category)&&(!term||x.join(' ').toLowerCase().includes(term)));grid.innerHTML=rows.map(x=>`<article class="vault-card"><small>${x[0]}</small><h4>${x[1]}</h4><p>${x[2]}</p><button class="copy" data-title="${x[1]}">Copy Ready Prompt</button><button class="copy practice" data-practice="${x[1]}">Practice with Harper</button></article>`).join('')||'<p>No exact match. Ask Harper to find the nearest workflow.</p>';grid.querySelectorAll('[data-title]').forEach(button=>button.onclick=async()=>{const prompt=prompts.find(x=>x[1]===button.dataset.title)[2];try{await navigator.clipboard.writeText(prompt);button.textContent='Copied'}catch{button.textContent='Copy unavailable'}});grid.querySelectorAll('[data-practice]').forEach(button=>button.onclick=()=>{openAssistant();setGuideMode('prompt',document.querySelectorAll('.role-tabs button')[3]);document.getElementById('askInput').value=`Help me use ${button.dataset.practice}.`})}search.oninput=render;select.onchange=render;render();
const cleanup=document.createElement('script');cleanup.src='commercial-cleanup.js';cleanup.onerror=()=>console.error('Commercial playbook cleanup failed to load');document.body.appendChild(cleanup);
const guide=document.createElement('script');guide.src='connections-guide.js';guide.onerror=()=>console.error('Setup and connections guide failed to load');document.body.appendChild(guide);
})();
