const crypto=require('crypto');
const COOKIE='ocg_lender_ai_cred';
function keyMaterial(){const raw=String(process.env.CREDENTIAL_ENCRYPTION_KEY||'').trim();if(!raw)throw new Error('CREDENTIAL_ENCRYPTION_NOT_CONFIGURED');return crypto.createHash('sha256').update(raw).digest()}
function parseCookies(req){const out={};String(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});return out}
function encrypt(value){const iv=crypto.randomBytes(12);const cipher=crypto.createCipheriv('aes-256-gcm',keyMaterial(),iv);const enc=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);const tag=cipher.getAuthTag();return Buffer.concat([iv,tag,enc]).toString('base64url')}
function decrypt(token){const b=Buffer.from(token,'base64url');const iv=b.subarray(0,12),tag=b.subarray(12,28),enc=b.subarray(28);const d=crypto.createDecipheriv('aes-256-gcm',keyMaterial(),iv);d.setAuthTag(tag);return Buffer.concat([d.update(enc),d.final()]).toString('utf8')}
function cookie(value,maxAge){return `${COOKIE}=${encodeURIComponent(value)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`}
async function validateGemini(key){const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models?key=${encodeURIComponent(key)}`,{headers:{accept:'application/json'}});if(!r.ok)throw new Error(`CUSTOMER_MODEL_${r.status}`);return true}
module.exports.getCustomerKey=function(req){const token=parseCookies(req)[COOKIE];if(!token)return '';try{return decrypt(token)}catch{return ''}};
module.exports=async function handler(req,res){res.setHeader('Cache-Control','no-store');try{if(req.method==='GET'){const connected=Boolean(module.exports.getCustomerKey(req));return res.status(200).json({connected,credential_owner:connected?'customer':null,secrets_exposed:false})}if(req.method==='DELETE'){res.setHeader('Set-Cookie',cookie('',0));return res.status(200).json({connected:false})}if(req.method!=='POST')return res.status(405).json({error:'GET, POST, or DELETE required'});const key=String(req.body?.api_key||'').trim();if(!key)return res.status(400).json({error:'A customer-owned Gemini API key is required.'});await validateGemini(key);const token=encrypt(key);res.setHeader('Set-Cookie',cookie(token,60*60*24*30));return res.status(200).json({connected:true,credential_owner:'customer',secrets_exposed:false})}catch(e){console.error('credential error',e.message);const msg=e.message==='CREDENTIAL_ENCRYPTION_NOT_CONFIGURED'?'Secure credential storage is not configured yet.':e.message.startsWith('CUSTOMER_MODEL_')?'The supplied customer Gemini credential could not be validated.':'Credential connection failed.';return res.status(503).json({error:msg})}};
