const crypto=require('crypto');
const provider=require('./provider');
const CRED_COOKIE='ocg_lender_ai_cred';
const KEY_COOKIE='ocg_lender_ai_wrap';
function parseCookies(req){const out={};String(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});return out}
function cookie(name,value,maxAge){return `${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`}
function newWrapKey(){return crypto.randomBytes(32).toString('base64url')}
function keyMaterial(raw){const b=Buffer.from(String(raw||''),'base64url');if(b.length!==32)throw new Error('CUSTOMER_WRAP_KEY_INVALID');return b}
function encrypt(value,rawKey){const iv=crypto.randomBytes(12);const cipher=crypto.createCipheriv('aes-256-gcm',keyMaterial(rawKey),iv);const enc=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);const tag=cipher.getAuthTag();return Buffer.concat([iv,tag,enc]).toString('base64url')}
function decrypt(token,rawKey){const b=Buffer.from(token,'base64url');if(b.length<29)throw new Error('CUSTOMER_CREDENTIAL_INVALID');const iv=b.subarray(0,12),tag=b.subarray(12,28),enc=b.subarray(28);const d=crypto.createDecipheriv('aes-256-gcm',keyMaterial(rawKey),iv);d.setAuthTag(tag);return Buffer.concat([d.update(enc),d.final()]).toString('utf8')}
function getCustomerConfig(req){const c=parseCookies(req);if(!c[CRED_COOKIE]||!c[KEY_COOKIE])return null;try{return JSON.parse(decrypt(c[CRED_COOKIE],c[KEY_COOKIE]))}catch{return null}}
async function handler(req,res){res.setHeader('Cache-Control','no-store');try{if(req.method==='GET'){const cfg=getCustomerConfig(req);return res.status(200).json({connected:Boolean(cfg),credential_owner:cfg?'customer':null,provider:cfg?.provider||null,model:cfg?.model||null,endpoint_configured:Boolean(cfg?.endpoint),credential_storage:'encrypted_http_only_browser_isolated',secrets_exposed:false})}if(req.method==='DELETE'){res.setHeader('Set-Cookie',[cookie(CRED_COOKIE,'',0),cookie(KEY_COOKIE,'',0)]);return res.status(200).json({connected:false})}if(req.method!=='POST')return res.status(405).json({error:'GET, POST, or DELETE required'});const cfg={provider:String(req.body?.provider||'').trim().toLowerCase(),api_key:String(req.body?.api_key||'').trim(),model:String(req.body?.model||'').trim(),endpoint:String(req.body?.endpoint||'').trim().replace(/\/$/,'')};if(!cfg.provider||!cfg.api_key)return res.status(400).json({error:'Choose an AI provider and enter your own API credential.'});await provider.validate(cfg);const wrapKey=newWrapKey();res.setHeader('Set-Cookie',[cookie(KEY_COOKIE,wrapKey,60*60*24*30),cookie(CRED_COOKIE,encrypt(JSON.stringify(cfg),wrapKey),60*60*24*30)]);return res.status(200).json({connected:true,credential_owner:'customer',provider:cfg.provider,model:cfg.model||null,endpoint_configured:Boolean(cfg.endpoint),credential_storage:'encrypted_http_only_browser_isolated',secrets_exposed:false})}catch(e){console.error('credential error',e.message);const msg=e.message==='CUSTOMER_ENDPOINT_REQUIRED'?'This provider needs its API base URL.':e.message==='CUSTOMER_PROVIDER_UNSUPPORTED'?'That provider type is not supported by this connector yet. Choose OpenAI-compatible for providers with a compatible API.':e.message.startsWith('CUSTOMER_MODEL_')?'The supplied customer AI credential could not be validated with that provider.':'AI connection failed.';return res.status(503).json({error:msg})}}
handler.getCustomerConfig=getCustomerConfig;
module.exports=handler;
