const K='ocg_leadflow_ai_pro_family_v3';
const LEGACY=['ocg_leadflow_ai_pro_family_v2','ocg_leadflow_ai_pro_v1'];
const DEFAULT={version:3,profile:{},rules:[],leads:[],connections:{},permissions:{},practice:{runs:0,passed:0,history:[]},actions:[],events:[],selectedLeadId:null};
const $=id=>document.getElementById(id);
const clone=o=>JSON.parse(JSON.stringify(o));
function normalize(raw){const s={...clone(DEFAULT),...(raw||{})};s.profile=s.profile||{};s.rules=Array.isArray(s.rules)?s.rules:[];s.leads=Array.isArray(s.leads)?s.leads:[];s.connections=s.connections||{};s.permissions=s.permissions||{};s.actions=Array.isArray(s.actions)?s.actions:[];s.events=Array.isArray(s.events)?s.events:[];if(typeof s.practice==='number')s.practice={runs:s.practice,passed:0,history:[]};s.practice={...DEFAULT.practice,...(s.practice||{})};s.version=3;return s}
function load(){try{const cur=localStorage.getItem(K);if(cur)return normalize(JSON.parse(cur));for(const k of LEGACY){const x=localStorage.getItem(k);if(x){const migrated=normalize(JSON.parse(x));localStorage.setItem(K,JSON.stringify(migrated));return migrated}}}catch(e){}return clone(DEFAULT)}
let S=load();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const now=()=>new Date().toISOString();
function id(prefix='id'){return prefix+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7)}
function persist(){try{localStorage.setItem(K,JSON.stringify(S))}catch(e){}renderAll()}
function log(type,text,leadId=null,meta={}){S.events.unshift({id:id('evt'),ts:now(),type,text,leadId,meta});S.events=S.events.slice(0,300)}
function toast(text){let t=$('lfToast');if(!t){t=document.createElement('div');t.id='lfToast';t.style.cssText='position:fixed;right:22px;bottom:22px;z-index:99;background:#0c1830;color:#fff;padding:12px 15px;border-radius:14px;box-shadow:0 16px 40px rgba(0,0,0,.22);opacity:0;transform:translateY(8px);transition:.2s;font-size:12px;font-weight:800';document.body.appendChild(t)}t.textContent=text;t.style.opacity='1';t.style.transform='none';clearTimeout(t._timer);t._timer=setTimeout(()=>{t.style.opacity='0';t.style.transform='translateY(8px)'},1800)}
function saveProfile(){S.profile={name:$('employeeName').value.trim(),business:$('businessName').value.trim(),type:$('businessType').value.trim(),area:$('serviceArea').value.trim(),hours:$('hours').value.trim()};log('training','Employee profile updated');persist();toast('Employee profile saved')}
function teachRule(){const t=$('ruleInput').value.trim();if(!t)return;S.rules.unshift({id:id('rule'),text:t,ts:now(),active:true,kind:'instruction'});$('ruleInput').value='';log('training','New operating rule added');persist();toast('Training saved')}
function improveRule(){const t=$('improveInput').value.trim();if(!t)return;S.rules.unshift({id:id('rule'),text:t,ts:now(),active:true,kind:'correction',priority:'newest'});$('improveInput').value='';log('training','Owner correction saved');persist();toast('Correction persisted')}
function removeRule(i){const r=S.rules[i];if(!r)return;S.rules.splice(i,1);log('training','Operating rule removed');persist()}
function rulesText(){return S.rules.filter(r=>r.active!==false).map(r=>r.text.toLowerCase()).join(' ')}
function seedDemo(){if(!S.leads.some(x=>x.name.toLowerCase()==='robert')){const l={id:id('lead'),name:'Robert',source:'Website',contact:'',need:'Kitchen remodel estimate',stage:'Qualified',priority:'High',history:[{ts:now(),channel:'Website',text:'Website inquiry received'},{ts:now(),channel:'Note',text:'Asked about budget and timing'},{ts:now(),channel:'Message',text:'Robert replied: aiming for next month'}],missing:['Property address'],appointment:'Not booked',followup:'Follow up today',followupAt:new Date().toISOString(),risk:'Waiting on address',next:'Ask for property address and preferred walkthrough times',owner:'Owner',updatedAt:now()};S.leads.push(l);S.selectedLeadId=l.id;log('lead','Robert demo relationship loaded',l.id)}persist();toast('Robert lead loaded')}
function addLead(){ensureOpsUI();const name=$('lfLeadName').value.trim();const need=$('lfLeadNeed').value.trim();if(!name){toast('Lead name is required');return}const lead={id:id('lead'),name,source:$('lfLeadSource').value.trim()||'Manual',contact:$('lfLeadContact').value.trim(),need:need||'Not specified',stage:'New',priority:'Medium',history:[{ts:now(),channel:'Manual',text:'Lead created in LeadFlow'}],missing:need?[]:['Need / reason for inquiry'],appointment:'Not booked',followup:'Needs qualification',followupAt:null,risk:need?'None identified':'Incomplete information',next:'Qualify the lead',owner:'Owner',updatedAt:now()};S.leads.unshift(lead);S.selectedLeadId=lead.id;log('lead','Lead created',lead.id);['lfLeadName','lfLeadNeed','lfLeadContact'].forEach(x=>$(x).value='');persist();toast('Lead added')}
function selectLead(leadId){S.selectedLeadId=leadId;persist()}
function selectedLead(){return S.leads.find(l=>l.id===S.selectedLeadId)||S.leads[0]||null}
function updateLeadField(field,value){const l=selectedLead();if(!l)return;l[field]=value;l.updatedAt=now();log('lead',field+' updated',l.id,{value});persist()}
function addLeadActivity(){const l=selectedLead();if(!l){toast('Select a lead first');return}const text=$('lfActivityText').value.trim();if(!text)return;const channel=$('lfActivityChannel').value;l.history=l.history||[];l.history.push({ts:now(),channel,text});l.updatedAt=now();$('lfActivityText').value='';log('activity',text,l.id,{channel});persist();toast('Activity added')}
function setFollowUp(){const l=selectedLead();if(!l)return;const dt=$('lfFollowAt').value;l.followupAt=dt?new Date(dt).toISOString():null;l.followup=dt?'Follow up '+new Date(dt).toLocaleString():'No scheduled follow-up';l.updatedAt=now();log('lead','Follow-up updated',l.id,{at:l.followupAt});persist()}
function leadSummary(l){if(!l)return'No matching lead is stored.';const hist=(l.history||[]).slice(-5).map(h=>h.channel+': '+h.text).join('; ')||'No activity stored';return `${l.name} wants ${l.need||'an unspecified service'}. Stage: ${l.stage||'Unknown'}. Priority: ${l.priority||'Medium'}. Recent history: ${hist}. Missing: ${(l.missing||[]).join(', ')||'nothing flagged'}. Appointment: ${l.appointment||'Not booked'}. Follow-up: ${l.followup||'Not scheduled'}. Risk: ${l.risk||'None identified'}. Recommended next action: ${l.next||'Review the lead'}.`}
function leadScore(l){let n=0;const text=((l.followup||'')+' '+(l.risk||'')+' '+(l.priority||'')).toLowerCase();if(/urgent|high/.test(text))n+=4;if(/today|overdue|late/.test(text))n+=3;if((l.missing||[]).length)n+=2;if(/stalled|waiting|incomplete/.test(text))n+=2;if(l.followupAt&&new Date(l.followupAt)<=new Date())n+=3;return n}
function attention(){return [...S.leads].map(l=>({l,score:leadScore(l)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score)}
function stalled(){const cutoff=Date.now()-3*86400000;return S.leads.filter(l=>{const last=l.history?.length?new Date(l.history[l.history.length-1].ts).getTime():0;return last<cutoff||/stalled|waiting/i.test((l.stage||'')+' '+(l.risk||''))})}
function practiceSend(){const t=$('practiceInput').value.trim();if(!t)return;addLine('practiceChat',t,'user');$('practiceInput').value='';const low=t.toLowerCase(),rules=rulesText();let ans='I would acknowledge the lead, use the stored business rules and collect only the information needed for the next decision.';let passed=true,flags=[];if(/urgent|leak|emergency|water|danger/.test(low)){if(rules.includes('emerg')||rules.includes('escalat'))ans='This appears urgent. Based on stored escalation training, I would collect essential contact/location details and escalate to a human now.';else{ans='This appears urgent, but no emergency/escalation rule is stored. I will not invent one. Add the rule before deployment.';passed=false;flags.push('missing escalation rule')}}else if(/after 6|after 5|evening/.test(low)){if(rules.includes('after 5'))ans='The stored rule prohibits scheduling after 5 PM. I would offer the next allowed time only after real calendar availability is confirmed.';else{ans='No late-appointment rule is stored. I cannot promise that time. Train the scheduling boundary first.';passed=false;flags.push('missing scheduling rule')}}else if(/derby/.test(low)){if((S.profile.area||'').toLowerCase().includes('derby')||rules.includes('derby'))ans='Derby is in the stored service area, so I can continue qualification.';else{ans='I cannot verify Derby from current training. I will not promise coverage until the service area is updated.';passed=false;flags.push('service area unknown')}}else if(/price|cost|how much/.test(low)){ans='I do not have verified pricing in this scenario. I would collect the needed context and either use stored approved pricing language or route this for human confirmation.';flags.push('pricing verification required')}
S.practice.runs++;if(passed)S.practice.passed++;S.practice.history.unshift({id:id('practice'),ts:now(),input:t,response:ans,passed,flags});S.practice.history=S.practice.history.slice(0,50);log('practice',passed?'Practice passed':'Practice exposed a training gap',null,{flags});persist();setTimeout(()=>addLine('practiceChat',ans,'ai'),120)}
function addLine(id,t,cls){const host=$(id);if(!host)return;const d=document.createElement('div');d.className='chat-line '+cls;d.textContent=t;host.appendChild(d);host.scrollTop=host.scrollHeight}
function manageAsk(){const q=$('manageInput').value.trim();if(!q)return;addLine('manageChat',q,'user');$('manageInput').value='';const low=q.toLowerCase();let a='';const exact=S.leads.find(l=>low.includes(l.name.toLowerCase()));if(exact)a=leadSummary(exact);else if(/who.*attention|needs.*attention|urgent|follow.?up.*due/.test(low)){const list=attention();a=list.length?'Needs attention: '+list.slice(0,8).map(x=>`${x.l.name} — ${x.l.followup||x.l.risk||x.l.next}`).join('; ')+'.':'No stored leads currently meet the attention rules.'}else if(/stall|stuck|not moving/.test(low)){const list=stalled();a=list.length?'Stalled / waiting: '+list.map(l=>`${l.name} — ${l.risk||l.stage}`).join('; ')+'.':'No stored leads are currently flagged as stalled.'}else if(/missing|need from/.test(low)){const list=S.leads.filter(l=>(l.missing||[]).length);a=list.length?list.map(l=>`${l.name}: ${(l.missing||[]).join(', ')}`).join('; '):'No missing-information flags are stored.'}else if(/appointment/.test(low)){a=S.leads.map(l=>`${l.name}: ${l.appointment||'Not booked'}`).join('; ')||'No leads stored.'}else a='I can answer from stored LeadFlow relationship memory. Ask about a lead by name, who needs attention, stalled leads, follow-ups, appointments, missing information or next actions.';log('query',q);setTimeout(()=>addLine('manageChat',a,'ai'),100)}
const INT=[['crm','CRM','Your existing CRM'],['email','Email','Lead-response mailbox'],['calendar','Calendar','Scheduling availability'],['sms','SMS / Text','Supported messaging provider'],['forms','Website Forms','Lead intake source'],['social','Social DMs','Supported business messaging']];
const BRIDGE=window.LeadFlowConnectorBridge=window.LeadFlowConnectorBridge||{executors:{},register(name,fn){this.executors[name]=fn;S.connections[name]={...(S.connections[name]||{}),technical:'connected',verifiedAt:now()};persist()},unregister(name){delete this.executors[name];S.connections[name]={...(S.connections[name]||{}),technical:'disconnected'};persist()},has(name){return typeof this.executors[name]==='function'},async execute(name,payload){if(!this.has(name))throw new Error(name+' connector is not technically connected');return await this.executors[name](payload)}};
function conn(k){const v=S.connections[k];if(typeof v==='boolean')return{intent:v,technical:'disconnected'};return{intent:false,technical:'disconnected',...(v||{})}}
function renderIntegrations(){const e=$('integrations');if(!e)return;e.innerHTML='';INT.forEach(x=>{const c=conn(x[0]),live=BRIDGE.has(x[0])||c.technical==='connected';const d=document.createElement('div');d.className='feature-card reveal in';d.innerHTML=`<div class="feature-icon">${x[1].slice(0,2).toUpperCase()}</div><h3>${x[1]}</h3><p>${x[2]}</p><div style="margin-top:14px"><span class="status-pill ${live?'green':c.intent?'gold':''}">${live?'TECHNICALLY CONNECTED':c.intent?'INTENT RECORDED':'NOT CONNECTED'}</span></div><div style="margin-top:12px"><button class="btn conn-btn">${c.intent?'Clear intent':'Record intent'}</button></div><p style="margin-top:10px;font-size:11px">${live?'Runtime connector registered and available.':'No live connector is registered. LeadFlow will draft or queue actions instead of claiming execution.'}</p>`;d.querySelector('.conn-btn').onclick=()=>toggleConn(x[0]);e.appendChild(d)})}
function toggleConn(k){const c=conn(k);S.connections[k]={...c,intent:!c.intent,technical:BRIDGE.has(k)?'connected':'disconnected'};log('connection',(S.connections[k].intent?'Connection intent recorded: ':'Connection intent cleared: ')+k);persist()}
function savePermissions(){document.querySelectorAll('[data-perm]').forEach(x=>S.permissions[x.dataset.perm]=x.checked);log('permission','Action permissions updated');persist();toast('Permissions saved')}
function queueAction(type,leadId,payload={}){const map={send:'send',schedule:'schedule',route:'route',modify:'modify',draft:'draft',escalate:'escalate'};const required=map[type]||type;const connector=payload.connector||({send:'email',schedule:'calendar'}[type]||null);let state='blocked',reason='Permission not granted';if(S.permissions[required]){if(type==='draft'||type==='escalate'||type==='route'||type==='modify'){state=type==='draft'?'ready':'queued';reason=type==='draft'?'Draft can be prepared locally':'Action requires owner/system completion'}else if(connector&&BRIDGE.has(connector)){state='ready';reason='Authorized connector is technically available'}else{state='queued';reason='Permission granted; waiting for a real connector'}}const a={id:id('act'),ts:now(),type,leadId,payload,requiredPermission:required,connector,state,reason,completedAt:null,result:null};S.actions.unshift(a);log('action',`${type} action ${state}`,leadId,{actionId:a.id});persist();return a}
async function executeAction(actionId){const a=S.actions.find(x=>x.id===actionId);if(!a)return;if(a.state==='blocked'){toast(a.reason);return}if(a.connector&&!BRIDGE.has(a.connector)){a.state='queued';a.reason='No technical '+a.connector+' connector is available. Nothing was sent or scheduled.';persist();toast(a.reason);return}if(a.connector){try{a.state='executing';persist();const result=await BRIDGE.execute(a.connector,a.payload);a.state='completed';a.completedAt=now();a.result=result||{ok:true};a.reason='Completed by registered connector';log('action',a.type+' completed',a.leadId,{actionId:a.id})}catch(e){a.state='failed';a.reason=String(e.message||e);log('action',a.type+' failed',a.leadId,{actionId:a.id,error:a.reason})}}else{a.state='completed';a.completedAt=now();a.result={ok:true,mode:'local'};a.reason='Completed as a local LeadFlow operation';log('action',a.type+' completed locally',a.leadId,{actionId:a.id})}persist()}
function createDraftForSelected(){const l=selectedLead();if(!l)return toast('Select a lead');const text=`Hi ${l.name}, I’m following up about ${l.need}. ${l.next||'What would be the best next step for you?'}`;queueAction('draft',l.id,{text,channel:'review'});toast('Draft queued for review')}
function recalc(){const c=[['Employee named',!!S.profile.name],['Business identified',!!S.profile.business],['Service area captured',!!S.profile.area],['At least 3 persistent instructions',S.rules.length>=3],['At least 2 practice runs',S.practice.runs>=2],['At least 1 practice pass',S.practice.passed>=1],['Permissions reviewed',Object.keys(S.permissions).length>=3],['Connection intent reviewed',Object.keys(S.connections).length>=1],['No unresolved critical training gap',!S.practice.history.slice(0,3).some(x=>!x.passed&&x.flags?.some(f=>/escalation/.test(f)))]];const pct=Math.round(c.filter(x=>x[1]).length/c.length*100);if($('readyBar'))$('readyBar').style.width=pct+'%';if($('readyText'))$('readyText').textContent=pct+'% ready';if($('deployChecks'))$('deployChecks').innerHTML=c.map(x=>`<div class="check">${x[1]?'✓':'○'} ${x[0]}</div>`).join('');return pct}
function exportDNA(){const data={product:'LeadFlow AI Receptionist & Follow-Up System',series:'OCG LAB AI PRO',version:'3.0',positioning:'Train Your Own AI Lead Employee',exported:now(),profile:S.profile,instructions:S.rules.filter(r=>r.active!==false),permissions:S.permissions,intendedConnections:S.connections,truthfulness:{neverInventLeadFacts:true,neverClaimUnavailableConnector:true,neverClaimUnverifiedAction:true},leadSchema:['identity','need','history','missing','appointment','followup','risk','next']};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='LeadFlow_AI_DNA.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),300);log('export','AI DNA exported');persist()}
function exportWorkspace(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.download='LeadFlow_Workspace_Backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),300);toast('Workspace backup exported')}
function ensureOpsUI(){const host=$('leadList')?.parentElement;if(!host||$('lfLeadOps'))return;const wrap=document.createElement('div');wrap.id='lfLeadOps';wrap.innerHTML=`<div style="margin-top:18px;border-top:1px solid #e0e8f1;padding-top:18px"><h3>Add a real lead</h3><div class="field"><label>Name</label><input id="lfLeadName" placeholder="Lead name"></div><div class="field"><label>Need / inquiry</label><input id="lfLeadNeed" placeholder="What do they need?"></div><div class="field"><label>Contact</label><input id="lfLeadContact" placeholder="Phone or email"></div><div class="field"><label>Source</label><input id="lfLeadSource" placeholder="Website, call, referral..."></div><button class="btn primary" onclick="addLead()">Add Lead</button></div><div id="lfLeadDetail" style="margin-top:18px"></div>`;host.appendChild(wrap);const manage=$('manage');if(manage&&!$('lfActionQueue')){const box=document.createElement('div');box.className='install-panel reveal in';box.style.marginTop='18px';box.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center;gap:12px"><div><div class="eyebrow" style="margin-bottom:5px">ACTION STATE</div><h3 style="margin:0">Truthful action queue</h3></div><button class="btn" onclick="exportWorkspace()">Backup Workspace</button></div><p style="color:#627487;font-size:13px">Drafts and actions stay queued until permissions and real connector capability allow execution.</p><div id="lfActionQueue"></div>';manage.querySelector('.shell').appendChild(box)}}
function renderLeadDetail(){const host=$('lfLeadDetail');if(!host)return;const l=selectedLead();if(!l){host.innerHTML='<div class="muted">Select or add a lead to manage its full relationship memory.</div>';return}const hist=(l.history||[]).slice().reverse().slice(0,8).map(h=>`<div class="row"><div><b>${esc(h.channel||'Activity')}</b><small>${esc(h.text)}<br>${new Date(h.ts).toLocaleString()}</small></div></div>`).join('');host.innerHTML=`<div style="border-top:1px solid #e0e8f1;padding-top:18px"><div class="eyebrow" style="margin-bottom:5px">SELECTED RELATIONSHIP</div><h3>${esc(l.name)}</h3><div class="field"><label>Stage</label><select onchange="updateLeadField('stage',this.value)">${['New','Qualified','Appointment','Proposal','Waiting','Won','Lost'].map(x=>`<option ${l.stage===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Priority</label><select onchange="updateLeadField('priority',this.value)">${['High','Medium','Low'].map(x=>`<option ${l.priority===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Next action</label><input value="${esc(l.next||'')}" onchange="updateLeadField('next',this.value)"></div><div class="field"><label>Risk / blocker</label><input value="${esc(l.risk||'')}" onchange="updateLeadField('risk',this.value)"></div><div class="field"><label>Follow-up date/time</label><input id="lfFollowAt" type="datetime-local"><button class="btn" style="margin-top:8px" onclick="setFollowUp()">Set Follow-Up</button></div><div class="hero-actions" style="margin:12px 0"><button class="btn primary" onclick="createDraftForSelected()">Create Follow-Up Draft</button><button class="btn" onclick="queueAction('schedule','${l.id}',{connector:'calendar',lead:'${esc(l.name)}'})">Queue Scheduling</button><button class="btn" onclick="queueAction('escalate','${l.id}',{lead:'${esc(l.name)}'})">Escalate</button></div><div class="field"><label>Add relationship activity</label><select id="lfActivityChannel"><option>Call</option><option>Text</option><option>Email</option><option>Note</option><option>Appointment</option></select><textarea id="lfActivityText" placeholder="What happened? What did the lead say? What did we commit to?"></textarea><button class="btn" style="margin-top:8px" onclick="addLeadActivity()">Add Activity</button></div><h4>Recent relationship history</h4>${hist||'<div class="muted">No activity yet.</div>'}</div>`}
function renderActions(){const host=$('lfActionQueue');if(!host)return;host.innerHTML=S.actions.length?S.actions.slice(0,15).map(a=>{const lead=S.leads.find(l=>l.id===a.leadId);return `<div class="row"><div><b>${esc(a.type.toUpperCase())} · ${esc(lead?.name||'General')}</b><small>${esc(a.reason)}<br>${new Date(a.ts).toLocaleString()}</small></div><div><span class="status-pill ${a.state==='completed'?'green':a.state==='blocked'||a.state==='failed'?'':'gold'}">${esc(a.state)}</span>${['ready','queued'].includes(a.state)?`<button class="btn" style="margin-left:8px" onclick="executeAction('${a.id}')">Attempt</button>`:''}</div></div>`}).join(''):'<div class="muted">No actions queued.</div>'}
function renderAttention(){const hero=$('heroRobert');const top=attention()[0];if(top)hero.textContent=leadSummary(top.l);else hero.textContent='No stored lead currently needs attention. Add leads or load the Robert demo to start.'}
function renderAll(){ensureOpsUI();const n=S.profile.name||'Your AI Lead Employee';if($('agentLabel'))$('agentLabel').textContent=n;['employeeName','businessName','businessType','serviceArea','hours'].forEach((el,i)=>{const node=$(el),k=['name','business','type','area','hours'][i];if(node&&document.activeElement!==node)node.value=S.profile[k]||''});if($('trainingList'))$('trainingList').innerHTML=S.rules.length?S.rules.map((r,i)=>`<div class="row"><div><b>${r.kind==='correction'?'Correction':'Instruction'}</b><small>${esc(r.text)}</small></div><button class="btn" onclick="removeRule(${i})">Remove</button></div>`).join(''):'<div class="muted">No business instructions saved yet.</div>';if($('leadList'))$('leadList').innerHTML=S.leads.length?S.leads.map(l=>`<button class="row" style="width:100%;text-align:left;cursor:pointer;${l.id===S.selectedLeadId?'border-color:#72aaff;box-shadow:0 0 0 3px rgba(23,108,255,.06)':''}" onclick="selectLead('${l.id}')"><div><b>${esc(l.name)}</b><small>${esc(l.need)}<br>${esc(l.followup||'No follow-up')} · ${esc(l.stage||'New')}</small></div><span class="status-pill ${leadScore(l)>=5?'gold':''}">${esc(l.priority||'Medium')}</span></button>`).join(''):'<div class="muted">No leads stored yet.</div>';renderIntegrations();document.querySelectorAll('[data-perm]').forEach(x=>x.checked=!!S.permissions[x.dataset.perm]);renderLeadDetail();renderActions();renderAttention();recalc()}
const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('in')),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));renderAll();