(function(){
  const endpoint='/api/leadflow-ai';
  const storageKey='ocg_leadflow_ai_pro_family_v3';
  let liveState='checking';
  function state(){try{return JSON.parse(localStorage.getItem(storageKey)||'{}')}catch(e){return{}}}
  function status(text,tone=''){
    let el=document.getElementById('lfAiStatus');
    if(!el){const anchor=document.getElementById('agentLabel');if(!anchor)return;el=document.createElement('span');el.id='lfAiStatus';el.className='status-pill';el.style.marginLeft='8px';anchor.parentElement.insertBefore(el,anchor.nextSibling)}
    el.textContent=text;el.className='status-pill '+tone;
  }
  async function health(){try{const r=await fetch(endpoint,{cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json();if(!d.configured){liveState='fallback';status('LOCAL MODE','gold');return d}liveState='ready';status('LIVE AI','green');return d}catch(e){liveState='fallback';status('LOCAL MODE','gold');return null}}
  function contextLead(message){const s=state(),low=String(message||'').toLowerCase();return (s.leads||[]).find(l=>low.includes(String(l.name||'').toLowerCase()))||(s.leads||[]).find(l=>l.id===s.selectedLeadId)||(s.leads||[])[0]||{}}
  async function askAI(mode,message,lead={}){const s=state(),payload={mode,message,profile:s.profile||{},rules:s.rules||[],permissions:s.permissions||{},connections:s.connections||{},lead};const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok||!d.text)throw new Error(d.error||'Live AI unavailable');return d.text}
  function score(l){let n=0;const t=((l.followup||'')+' '+(l.risk||'')+' '+(l.priority||'')).toLowerCase();if(/urgent|high/.test(t))n+=4;if(/today|overdue|late/.test(t))n+=3;if((l.missing||[]).length)n+=2;if(/stalled|waiting|incomplete/.test(t))n+=2;if(l.followupAt&&new Date(l.followupAt)<=new Date())n+=3;return n}
  function summary(l){if(!l)return'No matching lead is stored.';const hist=(l.history||[]).slice(-5).map(h=>(h.channel||'Activity')+': '+h.text).join('; ')||'No activity stored';return `${l.name} wants ${l.need||'an unspecified service'}. Stage: ${l.stage||'Unknown'}. Priority: ${l.priority||'Medium'}. Recent history: ${hist}. Missing: ${(l.missing||[]).join(', ')||'nothing flagged'}. Appointment: ${l.appointment||'Not booked'}. Follow-up: ${l.followup||'Not scheduled'}. Risk: ${l.risk||'None identified'}. Recommended next action: ${l.next||'Review the lead'}.`}
  function deterministicManage(q){const s=state(),low=q.toLowerCase(),exact=(s.leads||[]).find(l=>low.includes(String(l.name||'').toLowerCase()));if(exact)return summary(exact);if(/who.*attention|needs.*attention|urgent|follow.?up.*due/.test(low)){const list=(s.leads||[]).map(l=>({l,score:score(l)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);return list.length?'Needs attention: '+list.slice(0,8).map(x=>`${x.l.name} — ${x.l.followup||x.l.risk||x.l.next}`).join('; ')+'.':'No stored leads currently meet the attention rules.'}if(/stall|stuck|not moving/.test(low)){const cutoff=Date.now()-3*86400000,list=(s.leads||[]).filter(l=>{const last=l.history?.length?new Date(l.history[l.history.length-1].ts).getTime():0;return last<cutoff||/stalled|waiting/i.test((l.stage||'')+' '+(l.risk||''))});return list.length?'Stalled / waiting: '+list.map(l=>`${l.name} — ${l.risk||l.stage}`).join('; ')+'.':'No stored leads are currently flagged as stalled.'}if(/missing|need from/.test(low)){const list=(s.leads||[]).filter(l=>(l.missing||[]).length);return list.length?list.map(l=>`${l.name}: ${(l.missing||[]).join(', ')}`).join('; '):'No missing-information flags are stored.'}return'I can answer from stored LeadFlow relationship memory. Ask about a lead by name, who needs attention, stalled leads, follow-ups, appointments, missing information or next actions.'}
  window.manageAsk=async function(){const input=document.getElementById('manageInput'),q=input?.value.trim();if(!q)return;if(typeof window.addLine==='function')window.addLine('manageChat',q,'user');input.value='';let answer='';try{status('THINKING…','gold');answer=await askAI('manage',q,contextLead(q));liveState='ready';status('LIVE AI','green')}catch(e){liveState='fallback';status('LOCAL MODE','gold');answer=deterministicManage(q)}if(typeof window.addLine==='function')window.addLine('manageChat',answer,'ai')};
  function installPracticeCoach(){const send=document.querySelector('#practice button[onclick="practiceSend()"]');if(!send||document.getElementById('lfLivePractice'))return;const b=document.createElement('button');b.id='lfLivePractice';b.className='btn';b.textContent='Live AI Coach';b.style.marginLeft='8px';b.onclick=async()=>{const input=document.getElementById('practiceInput'),q=input?.value.trim();if(!q)return;if(typeof window.addLine==='function')window.addLine('practiceChat',q,'user');input.value='';try{status('THINKING…','gold');const a=await askAI('practice',q,contextLead(q));status('LIVE AI','green');if(typeof window.addLine==='function')window.addLine('practiceChat',a,'ai')}catch(e){status('LOCAL MODE','gold');if(typeof window.addLine==='function')window.addLine('practiceChat','Live AI is unavailable right now. Use the standard Send button for deterministic training-rule testing.','ai')}};send.after(b)}
  window.LeadFlowLiveAI={health,ask:askAI,get state(){return liveState}};
  health();installPracticeCoach();
})();
